#!/bin/bash
cd /usr/local/xcap/drivers
rmmod pixci
rm /lib/modules/5.4.0-58-generic/kernel/drivers/misc/pixci.ko
./pixci.sh install /usr/local/xcap/drivers /usr/local/xcap/drivers/x86_64/5.4.0-58-generic
